// load studyList
export const GET_ONLINE_STUDY_LIST = 'GET_ONLINE_STUDY_LIST';
export const GET_OFFLINE_STUDY_LIST = 'GET_OFFLINE_STUDY_LIST';

// login
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

// myPage (당도, 스크랩수, 닉네임, 프로필사진)
export const GET_MY_PAGE = 'GET_MY_PAGE';
export const GET_MY_PAGE_SUCCESS = 'GET_MY_PAGE_SUCCESS';
export const GET_MY_PAGE_FAILURE = 'GET_MY_PAGE_FAILURE';

// scarpList
export const GET_SCRAP_LIST = 'GET_SCRAP_LIST';
export const GET_SCRAP_LIST_SUCCESS = 'GET_SCRAP_LIST_SUCCESS';
export const GET_SCRAP_LIST_FAILURE = 'GET_SCRAP_LIST_FAILURE';

// studyHistory (스터디 참여이력)
export const GET_STUDY_HISTORY = 'GET_STUDY_HISTORY';
export const GET_STUDY_HISTORY_SUCCESS = 'GET_STUDY_HISTORY_SUCCESS';
export const GET_STUDY_HISTORY_FAILURE = 'GET_STUDY_HISTORY_FAILURE';

// get my profile
export const GET_MY_PROFILE = 'GET_MY_PROFILE';
export const GET_MY_PROFILE_SUCCESS = 'GET_MY_PROFILE_SUCCESS';
export const GET_MY_PROFILE_FAILURE = 'GET_MY_PROFILE_FAILURE';

// get user profile
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

// 스터디 관리 (내 모집글)
export const GET_MY_STUDY_LIST = 'GET_MY_STUDY_LIST';
export const GET_MY_STUDY_LIST_SUCCESS = 'GET_MY_STUDY_LIST_SUCCESS';
export const GET_MY_STUDY_LIST_FAILURE = 'GET_MY_STUDY_LIST_FAILURE';

// 스터디 관리 (진행중)
export const GET_MY_APPLY_LIST = 'GET_MY_APPLY_LIST';
export const GET_MY_APPLY_LIST_SUCCESS = 'GET_MY_APPLY_LIST_SUCCESS';
export const GET_MY_APPLY_LIST_FAILURE = 'GET_MY_APPLY_LIST_FAILURE';

// 스터디원 관리 (member:스터디원, applyUser: 수락대기인원)
export const GET_STUDY_MEM_LIST = 'GET_STUDY_MEM_LIST';
export const GET_STUDY_MEM_LIST_SUCCESS = 'GET_STUDY_MEM_LIST_SUCCESS';
export const GET_STUDY_MEM_LIST_FAILURE = 'GET_STUDY_MEM_LIST_FAILURE';

// 스터디 디테일 정보
export const GET_STUDY_DETAIL = 'GET_STUDY_DETAIL';
export const GET_STUDY_DETAIL_SUCCESS = 'GET_STUDY_DETAIL_SUCCESS';
export const GET_STUDY_DETAIL_FAILURE = 'GET_STUDY_DETAIL_FAILURE';

// search (검색)
export const POST_STUDY_LIST = 'POST_STUDY_LIST';
export const POST_STUDY_LIST_SUCCESS = 'POST_STUDY_LIST_SUCCESS';
export const POST_STUDY_LIST_FAILURE = 'POST_STUDY_LIST_FAILURE';

export const REFRESH_STUDY_LIST = 'REFRESH_STUDY_LIST';
export const REFRESH_STUDY_LIST_SUCCESS = 'REFRESH_STUDY_LIST_SUCCESS';
export const REFRESH_STUDY_LIST_FAILURE = 'REFRESH_STUDY_LIST_FAILURE';

// searchHistory (검색기록)
export const GET_SEARCH_HISTORY_LIST = 'GET_SEARCH_HISTORY_LIST';
export const GET_SEARCH_HISTORY_LIST_SUCCESS =
  'GET_SEARCH_HISTORY_LIST_SUCCESS';
export const GET_SEARCH_HISTORY_LIST_FAILURE =
  'GET_SEARCH_HISTORY_LIST_FAILURE';

// searchAllDelete (검색기록 전체 삭제)
export const DELETE_ALL_SEARCH_HISTORY = 'DELETE_ALL_SEARCH_HISTORY';
export const DELETE_ALL_SEARCH_HISTORY_SUCCESS =
  'DELETE_ALL_SEARCH_HISTORY_SUCCESS';
export const DELETE_ALL_SEARCH_HISTORY_FAILURE =
  'DELETE_ALL_SEARCH_HISTORY_FAILURE';

//searchDelete ( 검색기록 하나 삭제 )
export const DELETE_SEARCH_HISTORY = 'DELETE_SEARCH_HISTORY';
export const DELETE_SEARCH_HISTORY_SUCCESS = 'DELETE_SEARCH_HISTORY_SUCCESS';
export const DELETE_SEARCH_HISTORY_FAILURE = 'DELETE_SEARCH_HISTORY_FAILURE';

//신고하기
//신고하기 클릭 -> 현재 참여중인 스터디만 조회
export const GET_STUDY_IN_PROGRESS = 'GET_STUDY_IN_PROGRESS';
export const GET_STUDY_IN_PROGRESS_SUCCESS = 'GET_STUDY_IN_PROGRESS_SUCCESS';
export const GET_STUDY_IN_PROGRESS_FAILURE = 'GET_STUDY_IN_PROGRESS_FAILURE';

//신고하기 상세
//스터디원 목록 출력
export const GET_STUDY_MEMBER = 'GET_STUDY_MEMBER';
export const GET_STUDY_MEMBER_SUCCESS = 'GET_STUDY_MEMBER_SUCCESS';
export const GET_STUDY_MEMBER_FAILURE = 'GET_STUDY_MEMBER_FAILURE';

//신고하기
export const POST_REPORT = 'POST_REPORT';
export const POST_REPORT_SUCCESS = 'POST_REPORT_SUCCESS';
export const POST_REPORT_FAILURE = 'POST_REPORT_FAILURE';

//상호평가
//상호평가 페이지 -> 상대 닉네임 & 프로필 출력
export const GET_EVALUATE_PROFILE = 'GET_EVALUATE_PROFILE';
export const GET_EVALUATE_PROFILE_SUCCESS = 'GET_EVALUATE_PROFILE_SUCCESS';
export const GET_EVALUATE_PROFILE_FAILURE = 'GET_EVALUATE_PROFILE_FAILURE';

//상호평가
export const GET_EVALUATE = 'GET_EVALUATE';
export const GET_EVALUATE_SUCCESS = 'GET_EVALUATE_SUCCESS';
export const GET_EVALUATE_FAILURE = 'GET_EVALUATE_FAILURE';

//회원 탈퇴
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
