// load studyList
export const GET_ONLINE_STUDY_LIST = 'GET_ONLINE_STUDY_LIST';
export const GET_OFFLINE_STUDY_LIST = 'GET_OFFLINE_STUDY_LIST';

// check nickname
export const CHECK_NICKNAME = 'CHECK_NICKNAME';

// login
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

// signup
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILURE = 'AUTH_SIGNUP_FAILURE';