// load studyList
export const GET_ONLINE_STUDY_LIST = 'GET_ONLINE_STUDY_LIST';
export const GET_OFFLINE_STUDY_LIST = 'GET_OFFLINE_STUDY_LIST';

// login
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

// myPage (당도, 스크랩수, 닉네임, 프로필사진)
export const GET_MY_PAGE = 'GET_MY_PAGE';
export const GET_MY_PAGE_SUCCESS = 'GET_MY_PAGE_SUCCESS';
export const GET_MY_PAGE_FAILURE = 'GET_MY_PAGE_FAILURE';

// scarpList
export const GET_SCRAP_LIST = 'GET_SCRAP_LIST';
export const GET_SCRAP_LIST_SUCCESS = 'GET_SCRAP_LIST_SUCCESS';
export const GET_SCRAP_LIST_FAILURE = 'GET_SCRAP_LIST_FAILURE';

// studyHistory (스터디 참여이력)
export const GET_STUDY_HISTORY = 'GET_STUDY_HISTORY';
export const GET_STUDY_HISTORY_SUCCESS = 'GET_STUDY_HISTORY_SUCCESS';
export const GET_STUDY_HISTORY_FAILURE = 'GET_STUDY_HISTORY_FAILURE';

// study detail
export const GET_STUDY_DETAIL = 'GET_STUDY_DETAIL';
export const GET_STUDY_DETAIL_SUCCESS = 'GET_STUDY_DETAIL_SUCCESS';
export const GET_STUDY_DETAIL_FAILURE = 'GET_STUDY_DETAIL_FAILURE';
